#!/bin/bash
display_menu() {
    clear
    echo "----------------------------------------------------------------"
    echo "             ✝️  Karaoke_Dashboard v4.6 (Stable) ✝️              "
    echo "----------------------------------------------------------------"
    echo "Active Assets:"
    jq -r 'to_entries[] | "  \(.key): \(.value)"' "$PRESETS"
    echo "----------------------------------------------------------------"
    echo "--- Media Tools ---"
    echo " 1) Split Stems"
    echo " 2) Optimize Volume"
    echo " 3) Strip Audio From Video"
    echo " 4) Join Background Videos"
    echo ""
    echo "--- Karaoke Tools ---"
    echo " 6) Import Assets"
    echo " 7) Create Karaoke Video"
    echo " 8) Create Lyrics Video"
    echo ""
    echo "--- System/Admin ---"
    echo " 9) Purge Outputs"
    echo " 10) Push to GitHub"
    echo " 11) Exit"
    echo "----------------------------------------------------------------"
}