display_menu() {
    clear
    echo "----------------------------------------------------------------"
    echo "             ✝️  Karaoke_Dashboard v4.6 (Stable) ✝️              "
    echo "----------------------------------------------------------------"
    echo "Active Assets:"
    jq -r 'to_entries[] | "  \(.key): \(.value)"' "$PRESETS"
    echo "----------------------------------------------------------------"
    echo "--- Media Tools ---"
    echo " 1) Split Stems"
    echo " 2) Import Audio Files & Optimize Volume"
    echo " 3) Strip Audio From Video"
    echo " 4) Import & Optimize Background Videos"
    echo " 5) Auto-Caption Subtitles (Whisper .srt Generator)"
    echo " 6) Import Production Subtitles (Manual .ass Import)"
    echo ""
    echo "--- Karaoke Tools ---"
    echo " 7) Open Web Browser Preview Room"
    echo " 8) Create Karaoke Video"
    echo " 9) Create Lyrics Video"
    echo ""
    echo "--- System/Admin ---"
    echo " 10) Purge Outputs"
    echo " 11) Push to GitHub"
    echo "----------------------------------------------------------------"
}